name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: mesytec-mvlc-clone
      run: git clone https://github.com/flueke/mesytec-mvlc
    - name: mesytec-mvlc-configure
      run: cd mesytec-mvlc && mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: mesytec-mvlc-build
      run: cd mesytec-mvlc && cmake --build build
    - name: mesytec-mvlc-test
      run: cd mesytec-mvlc && cd build && ctest
    - name: build
      run: export MVLC_DIR=`pwd`/mesytec-mvlc && make
    - name: example
      run: export MVLC_DIR=`pwd`/mesytec-mvlc && make -C example
